# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gramm/')),
                ('image_name', models.CharField(max_length=15)),
                ('image_caption', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=50)),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='gramm/')),
                ('biography', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='profile_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elle.Profile'),
        ),
    ]
