# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elle', '0002_remove_images_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='image_url',
        ),
    ]
