# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 09:50
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('elle', '0004_auto_20190523_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='image_url',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
